GET http://localhost:8080/api/vehicles
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDYxZTQ5MmE0ZTM5YzJhNmYwZjY3NGYiLCJ1c2VyTmFtZSI6IkN5cGhlciIsImZ1bGxOYW1lIjoiUmVhZ2FuIiwicm9sZSI6ImhhY2tlciIsImlhdCI6MTYxNzAyOTc2NX0.cPkfFrpW7QrdCsdhla9HFknrB6_5ns8-8IF78Md_7v0